import Head from 'next/head'
import Header from './Header'
import About from './About'
import Projects from './Projects'
import data from 'src/pages/data.js'

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <About />
      <Projects />
    </>
  )
}


// const project = data.map(item => {
//   return (
//     <Projects 
//       key={item.key}
//       description={item.description}
//     />
//   )
// })